from typing import Protocol

from app.domain.user import NewUser, User, UserChanges


class UserRepositoryPort(Protocol):
    async def create(self, data: NewUser) -> User: ...

    async def get_by_id(self, user_id: str) -> User: ...

    async def list_users(self, skip: int, limit: int) -> list[User]: ...

    async def update(self, user_id: str, changes: UserChanges) -> User: ...

    async def delete(self, user_id: str) -> None: ...
